In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns',None)

In [2]:
#load dataset
df = pd.read_csv('/Users/aryaapalande/Desktop/Superstore_sales_project/superstore_data_raw/Returns-Table 1.csv')

In [3]:
#preview dataset
df.head()

         Order ID Returned  Unnamed: 2  Unnamed: 3  Unnamed: 4
0  US-2023-100762      Yes         NaN         NaN         NaN
1  US-2023-100867      Yes         NaN         NaN         NaN
2  US-2023-102652      Yes         NaN         NaN         NaN
3  US-2023-103373      Yes         NaN         NaN         NaN
4  US-2023-103744      Yes         NaN         NaN         NaN

In [4]:
#dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296 entries, 0 to 295
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order ID    296 non-null    object
 1   Returned    296 non-null    object
 2   Unnamed: 2  0 non-null      float64
 3   Unnamed: 3  0 non-null      float64
 4   Unnamed: 4  0 non-null      float64
dtypes: float64(3), object(2)
memory usage: 11.7+ KB

In [5]:
df.columns

Index(['Order ID', 'Returned', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [6]:
df.shape

(296, 5)

In [7]:
df.describe(include='all')

              Order ID Returned  Unnamed: 2  Unnamed: 3  Unnamed: 4
count              296      296         0.0         0.0         0.0
unique             296        1         NaN         NaN         NaN
top     US-2023-100762      Yes         NaN         NaN         NaN
freq                 1      296         NaN         NaN         NaN
mean               NaN      NaN         NaN         NaN         NaN
std                NaN      NaN         NaN         NaN         NaN
min                NaN      NaN         NaN         NaN         NaN
25%                NaN      NaN         NaN         NaN         NaN
50%                NaN      NaN         NaN         NaN         NaN
75%                NaN      NaN         NaN         NaN         NaN
max                NaN      NaN         NaN         NaN         NaN

In [8]:
#missing values
df.isnull().sum()

Order ID        0
Returned        0
Unnamed: 2    296
Unnamed: 3    296
Unnamed: 4    296
dtype: int64

In [9]:
#duplicate rows
df.duplicated().sum()

np.int64(0)

In [10]:
#datatypes
df.dtypes

Order ID       object
Returned       object
Unnamed: 2    float64
Unnamed: 3    float64
Unnamed: 4    float64
dtype: object

In [11]:
#remove unnecessary column
df = df[['Order ID','Returned']]

In [12]:
#unique values
df['Order ID'].nunique()

296

In [13]:
df['Returned'].nunique()

1

In [14]:
df.isnull().sum()

Order ID    0
Returned    0
dtype: int64

In [15]:
#save cleaned dataset
df.to_csv("/Users/aryaapalande/Desktop/Superstore_sales_project/superstore_data_cleaned/returns_cleaned.csv", index=False)